# Generated by Django 3.2.11 on 2022-07-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynfilters', '0005_alter_dynamicfilterexpr_is_global'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicfiltercolumn',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='dynamicfiltercolumnsortorder',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='dynamicfilterexpr',
            name='is_global',
            field=models.BooleanField(db_index=True, default=False, help_text='Make filter accessible to all.', verbose_name='Global?'),
        ),
        migrations.AlterField(
            model_name='dynamicfilterterm',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
    ]
