# Generated by Django 3.2.11 on 2022-07-05 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynfilters', '0006_auto_20220705_0753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dynamicfilterterm',
            old_name='filter',
            new_name='dynamic_filter_expr',
        ),
    ]
