# Generated by Django 3.2.11 on 2022-07-05 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynfilters', '0007_rename_filter_dynamicfilterterm_dynamic_filter_expr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicfiltercolumnsortorder',
            name='filter',
        ),
        migrations.DeleteModel(
            name='DynamicFilterColumn',
        ),
        migrations.DeleteModel(
            name='DynamicFilterColumnSortOrder',
        ),
    ]
