# Generated by Django 3.2.11 on 2022-07-05 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynfilters', '0008_auto_20220705_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicfilterterm',
            name='field',
        ),
    ]
