# Generated by Django 3.2.11 on 2022-07-05 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynfilters', '0009_remove_dynamicfilterterm_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamicfilterexpr',
            options={'verbose_name': 'Filter a', 'verbose_name_plural': 'Filters a'},
        ),
        migrations.RenameField(
            model_name='dynamicfilterexpr',
            old_name='model',
            new_name='model_name',
        ),
    ]
