# Generated by Django 3.2.11 on 2022-07-05 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynfilters', '0010_auto_20220705_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicfilterterm',
            name='bilateral',
        ),
        migrations.RemoveField(
            model_name='dynamicfilterterm',
            name='lookup',
        ),
        migrations.RemoveField(
            model_name='dynamicfilterterm',
            name='op',
        ),
        migrations.RemoveField(
            model_name='dynamicfilterterm',
            name='value',
        ),
    ]
