# Generated by Django 3.2.11 on 2022-07-05 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynfilters', '0011_auto_20220705_0944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamicfilterexpr',
            options={'verbose_name': 'Filter', 'verbose_name_plural': 'Filters'},
        ),
        migrations.RenameField(
            model_name='dynamicfilterexpr',
            old_name='model_name',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='dynamicfilterterm',
            old_name='dynamic_filter_expr',
            new_name='filter',
        ),
        migrations.AddField(
            model_name='dynamicfilterterm',
            name='bilateral',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dynamicfilterterm',
            name='field',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='dynamicfilterterm',
            name='lookup',
            field=models.CharField(choices=[('-', '---------'), ('=', 'Equals'), ('icontains', 'Contains'), ('istartswith', 'Starts with'), ('iendswith', 'Ends with'), ('in', 'One of'), ('-', '---------'), ('range', 'Date Range'), ('year', 'Date Year'), ('month', 'Date Month'), ('day', 'Date Day'), ('-', '---------'), ('isnull', 'Is NULL'), ('isnotnull', 'Is not NULL'), ('istrue', 'Is TRUE'), ('isfalse', 'Is FALSE'), ('-', '---------'), ('lt', 'Less Than'), ('gt', 'Greater Than'), ('lte', 'Less Than or Equal To'), ('gte', 'Greater Than or Equal To')], default='-', max_length=16),
        ),
        migrations.AddField(
            model_name='dynamicfilterterm',
            name='op',
            field=models.CharField(choices=[('-', '-'), ('!', 'NOT'), ('&', 'AND'), ('|', 'OR'), ('(', '('), (')', ')')], default='-', max_length=1),
        ),
        migrations.AddField(
            model_name='dynamicfilterterm',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='DynamicFilterColumnSortOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(blank=True, max_length=64, null=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynfilters.dynamicfilterexpr')),
            ],
            options={
                'verbose_name': 'Column sort order',
                'verbose_name_plural': 'Column sort orders',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='DynamicFilterColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(blank=True, max_length=64, null=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynfilters.dynamicfilterexpr')),
            ],
            options={
                'verbose_name': 'Column',
                'verbose_name_plural': 'Columns',
                'ordering': ('order',),
            },
        ),
    ]
