# Generated by Django 3.2.11 on 2022-09-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynfilters', '0012_auto_20220705_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicfilterterm',
            name='lookup',
            field=models.CharField(choices=[('-', '---------'), ('=', 'Equals'), ('icontains', 'Contains'), ('icontains_one_of', 'Contains one of'), ('icontains_all_of', 'Contains all of'), ('istartswith', 'Starts with'), ('iendswith', 'Ends with'), ('in', 'One of'), ('-', '---------'), ('range', 'Date Range'), ('year', 'Date Year'), ('month', 'Date Month'), ('day', 'Date Day'), ('-', '---------'), ('isnull', 'Is NULL'), ('isnotnull', 'Is not NULL'), ('istrue', 'Is TRUE'), ('isfalse', 'Is FALSE'), ('-', '---------'), ('lt', 'Less Than'), ('gt', 'Greater Than'), ('lte', 'Less Than or Equal To'), ('gte', 'Greater Than or Equal To'), ('-', '---- JSONField ----'), ('has_key', 'Has key'), ('contains_json', 'Contains JSON')], default='-', max_length=16),
        ),
    ]
